'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'..');
function setup(){const elements={};const get=id=>elements[id]??={value:id==='filter'?'all':'',innerHTML:'',textContent:'',focus(){}};const context=vm.createContext({document:{getElementById:get,querySelectorAll:()=>[],addEventListener(){}},console});vm.runInContext(fs.readFileSync(path.join(root,'assets/dashboard.js'),'utf8'),context);return {get,run:s=>vm.runInContext(s,context)}}
test('portfolio reconciles to 200M EAD and 12.22548M EL',()=>{const {run}=setup();assert(Math.abs(run('total')-200)<1e-9);assert(Math.abs(run('loss')-12.22548)<1e-9);assert(run('DATA.every(r=>Math.abs(r.el-r.ead*r.pd/100*r.lgd/100)<1e-9)'))});
test('signed contributions reconcile and PD is bounded',()=>{const {run}=setup();assert(run('DATA.every(r=>r.pd>=0&&r.pd<=100&&Math.abs(r.base+r.drivers.reduce((a,b)=>a+b,0)-r.pd)<1e-9)'))});
test('watchlist, breach filter, sorting and empty state',()=>{const {get,run}=setup();get('filter').value='watch';assert.equal(run('visible().length'),4);get('filter').value='breach';assert.equal(run('visible().length'),3);get('filter').value='all';run("sortKey='pd';sortDir=1");assert.equal(run('visible()[0].name'),'Fenwick Medical Supplies');get('search').value='unmatched';run('render()');assert.match(get('rows').innerHTML,/No obligors/)});
test('DSCR scenario changes PD by defined amount and retains default',()=>{const {get,run}=setup();get('dscr').value='1.62';run('scenario(DATA[0])');assert.match(get('scenarioout').innerHTML,/5.00%/);get('dscr').value='2.5';run('scenario(DATA[5])');assert.match(get('scenarioout').innerHTML,/100.00%/)});
test('all local page assets and links resolve; watermark is present',()=>{for(const file of ['index.html','terms.html','dashboard.html']){const html=fs.readFileSync(path.join(root,file),'utf8');assert(html.includes('Aditya Makurwar / Ethen huntt'));for(const [,url] of html.matchAll(/(?:href|src)="([^"]+)"/g)){if(url.startsWith('#'))continue;assert(fs.existsSync(path.join(root,url.split(/[?#]/)[0])),`${file}: ${url}`)}}});
test('terms acknowledgment toggles entry and blocks unchecked submission',()=>{let accepted=false,destination=null,submit;const checkbox={checked:false,addEventListener:(_,fn)=>{accepted=fn}},button={disabled:true};const context=vm.createContext({document:{getElementById:id=>id==='accept'?checkbox:id==='enter'?button:{addEventListener:(_,fn)=>submit=fn}},window:{location:{assign:p=>destination=p}}});vm.runInContext(fs.readFileSync(path.join(root,'assets/terms.js'),'utf8'),context);submit({preventDefault(){}});assert.equal(destination,null);checkbox.checked=true;accepted();assert.equal(button.disabled,false);submit({preventDefault(){}});assert.equal(destination,'dashboard.html')});
